### ISSUE TITLE
Error on connecting to Slack

### ISSUE THREAD

**Issue by torkelrogstad** [CryptoFR/ln-tip-slack#29]
Upon pressing 'Add to Slack', and continuing after the first page, I get the following error: `error=Grant%3A%20missing%20session%20or%20misconfigured%20provider`. Any idea what might be causing this?

**Comment by mably** [comment]
Do you have admin rights on the related Slack?

**Comment by torkelrogstad** [comment]
Ah, I don't... Sorry for opening up an issue for this then, I haven't really used any Slack bots before.

**Comment by mably** [comment]
I'm not really an expert either.  I remember struggling quite a bit with that ;)

**Comment by torkelrogstad** [comment]
I just got admin status, but I keep getting the same error message... Might there be any other things causing it?

**Comment by mably** [comment]
It looks like you must first login on your Slack using the "Slack login" top menu entry before clicking on the Add to slack button.  Seems to be working fine on my test node.

**Comment by torkelrogstad** [comment]
Allright, it seems to be working! I'll fill up some funds and play with it tomorrow. Thanks for helping me!

**Comment by mably** [comment]
You're welcome :)

**Comment by torkelrogstad** [comment]
Allright, I've gotten a bit further in setting up my own server. In `slack-config.js.example`, there's two token settings. Where do I find these tokens?

**Comment by mably** [comment]
You must register you app here: https://api.slack.com/apps
And then you'll be able to get your app's credentials:
![image](https://user-images.githubusercontent.com/385653/37900529-b9a5f718-30ee-11e8-8dc9-3f89a85557d4.png)
