### ISSUE TITLE
Funds not restored when LN withdraw request fails

### ISSUE THREAD

**Issue by beinardus** [CryptoFR/ln-tip-slack#36]
I got a gateway timeout message during withdrawal of funds. The database was updated, but the withdrawal is not settled in LN. This should be an atomic transaction. I think this is the code responsable (module.withdrawFunds):

`							module.dbWithdrawFunds(sourceSlackId, amount).then(function (result) {
								var paymentRequest = { payment_request: payreq };
								logger.debug("Sending payment", paymentRequest);
								lightning.sendPaymentSync(paymentRequest, function (err, response) {
									if (err) {
										logger.debug("SendPayment Error:", err);
										err.error = err.message;
										reject(err);
									} else {
										logger.debug("SendPayment:", response);
										resolve(response);
									}
});`

This is a quite common scenario. If LN can't find a route with sufficient balance, it fails.

**Comment by mably** [comment]
We will fix the problem for now by just crediting back the funds to the account in case of LN payment error.   

You are welcome to review the related PR: https://github.com/CryptoFR/ln-tip-slack/pull/38

**Comment by mably** [comment]
https://ln-tip.com/ has been updated with latest master, so problem should be fixed.
